# Generated by Django 5.2.8 on 2025-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file1", models.FileField(upload_to="test_files/")),
                ("file2", models.FileField(upload_to="test_files/test_subfolder/")),
            ],
        ),
    ]
